"""
This file is auto generated by the code generation script.
Do not modify this file manually.
Use the `make codegen` command to regenerate.

当前文件为自动生成的控制 API 客户端代码。请勿手动修改此文件。
使用 `make codegen` 命令重新生成。

source: codegen/configs/memory_collection_control_api.yaml


Memory Collection 管控链路 API
"""

from typing import Dict, Optional

from alibabacloud_agentrun20250910.models import (
    CreateMemoryCollectionInput,
    CreateMemoryCollectionRequest,
    ListMemoryCollectionsOutput,
    ListMemoryCollectionsRequest,
    MemoryCollection,
    UpdateMemoryCollectionInput,
    UpdateMemoryCollectionRequest,
)
from alibabacloud_tea_openapi.exceptions._client import ClientException
from alibabacloud_tea_openapi.exceptions._server import ServerException
from alibabacloud_tea_util.models import RuntimeOptions
import pydash

from agentrun.utils.config import Config
from agentrun.utils.control_api import ControlAPI
from agentrun.utils.exception import ClientError, ServerError
from agentrun.utils.log import logger


class MemoryCollectionControlAPI(ControlAPI):
    """Memory Collection 管控链路 API"""

    def __init__(self, config: Optional[Config] = None):
        """初始化 API 客户端

        Args:
            config: 全局配置对象
        """
        super().__init__(config)

    def create_memory_collection(
        self,
        input: CreateMemoryCollectionInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """创建 Memory Collection

        Args:
            input: Memory Collection 配置

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: 创建的 Memory Collection 对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.create_memory_collection_with_options(
                CreateMemoryCollectionRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api create_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def create_memory_collection_async(
        self,
        input: CreateMemoryCollectionInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """创建 Memory Collection

        Args:
            input: Memory Collection 配置

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: 创建的 Memory Collection 对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.create_memory_collection_with_options_async(
                CreateMemoryCollectionRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api create_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def delete_memory_collection(
        self,
        memory_collection_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """删除 Memory Collection

        Args:
            memory_collection_name: Memory Collection 名称

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: 删除结果

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.delete_memory_collection_with_options(
                memory_collection_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api delete_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[memory_collection_name,]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    memory_collection_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def delete_memory_collection_async(
        self,
        memory_collection_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """删除 Memory Collection

        Args:
            memory_collection_name: Memory Collection 名称

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: 删除结果

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.delete_memory_collection_with_options_async(
                memory_collection_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api delete_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[memory_collection_name,]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    memory_collection_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def update_memory_collection(
        self,
        memory_collection_name: str,
        input: UpdateMemoryCollectionInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """更新 Memory Collection

        Args:
            memory_collection_name: Memory Collection 名称
            input: Memory Collection 配置

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: 更新的 Memory Collection 对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.update_memory_collection_with_options(
                memory_collection_name,
                UpdateMemoryCollectionRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api update_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[memory_collection_name,input.to_map(),]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    memory_collection_name,
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def update_memory_collection_async(
        self,
        memory_collection_name: str,
        input: UpdateMemoryCollectionInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """更新 Memory Collection

        Args:
            memory_collection_name: Memory Collection 名称
            input: Memory Collection 配置

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: 更新的 Memory Collection 对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.update_memory_collection_with_options_async(
                memory_collection_name,
                UpdateMemoryCollectionRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api update_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[memory_collection_name,input.to_map(),]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    memory_collection_name,
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def get_memory_collection(
        self,
        memory_collection_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """获取 Memory Collection

        Args:
            memory_collection_name: Memory Collection 名称

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: Memory Collection 对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.get_memory_collection_with_options(
                memory_collection_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api get_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[memory_collection_name,]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    memory_collection_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def get_memory_collection_async(
        self,
        memory_collection_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> MemoryCollection:
        """获取 Memory Collection

        Args:
            memory_collection_name: Memory Collection 名称

            headers: 请求头
            config: 配置

        Returns:
            MemoryCollection: Memory Collection 对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.get_memory_collection_with_options_async(
                memory_collection_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api get_memory_collection, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[memory_collection_name,]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    memory_collection_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def list_memory_collections(
        self,
        input: ListMemoryCollectionsRequest,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> ListMemoryCollectionsOutput:
        """枚举 Memory Collection

        Args:
            input: 枚举的配置

            headers: 请求头
            config: 配置

        Returns:
            ListMemoryCollectionsOutput: Memory Collection 列表

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.list_memory_collections_with_options(
                input,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api list_memory_collections, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def list_memory_collections_async(
        self,
        input: ListMemoryCollectionsRequest,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> ListMemoryCollectionsOutput:
        """枚举 Memory Collection

        Args:
            input: 枚举的配置

            headers: 请求头
            config: 配置

        Returns:
            ListMemoryCollectionsOutput: Memory Collection 列表

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.list_memory_collections_with_options_async(
                input,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api list_memory_collections, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e
