"""
This file is auto generated by the code generation script.
Do not modify this file manually.
Use the `make codegen` command to regenerate.

当前文件为自动生成的控制 API 客户端代码。请勿手动修改此文件。
使用 `make codegen` 命令重新生成。

source: codegen/configs/knowledgebase_control_api.yaml


KnowledgeBase 管控链路 API
"""

from typing import Dict, Optional

from alibabacloud_agentrun20250910.models import (
    CreateKnowledgeBaseInput,
    CreateKnowledgeBaseRequest,
    KnowledgeBase,
    ListKnowledgeBasesOutput,
    ListKnowledgeBasesRequest,
    UpdateKnowledgeBaseInput,
    UpdateKnowledgeBaseRequest,
)
from alibabacloud_tea_openapi.exceptions._client import ClientException
from alibabacloud_tea_openapi.exceptions._server import ServerException
from alibabacloud_tea_util.models import RuntimeOptions
import pydash

from agentrun.utils.config import Config
from agentrun.utils.control_api import ControlAPI
from agentrun.utils.exception import ClientError, ServerError
from agentrun.utils.log import logger


class KnowledgeBaseControlAPI(ControlAPI):
    """KnowledgeBase 管控链路 API"""

    def __init__(self, config: Optional[Config] = None):
        """初始化 API 客户端

        Args:
            config: 全局配置对象
        """
        super().__init__(config)

    def create_knowledge_base(
        self,
        input: CreateKnowledgeBaseInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """创建知识库

        Args:
            input: 知识库配置

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 创建的知识库对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.create_knowledge_base_with_options(
                CreateKnowledgeBaseRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api create_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def create_knowledge_base_async(
        self,
        input: CreateKnowledgeBaseInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """创建知识库

        Args:
            input: 知识库配置

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 创建的知识库对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.create_knowledge_base_with_options_async(
                CreateKnowledgeBaseRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api create_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def delete_knowledge_base(
        self,
        knowledge_base_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """删除知识库

        Args:
            knowledge_base_name: 知识库名称

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 删除知识库的结果

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.delete_knowledge_base_with_options(
                knowledge_base_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api delete_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[knowledge_base_name,]}\n  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    knowledge_base_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def delete_knowledge_base_async(
        self,
        knowledge_base_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """删除知识库

        Args:
            knowledge_base_name: 知识库名称

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 删除知识库的结果

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.delete_knowledge_base_with_options_async(
                knowledge_base_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api delete_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[knowledge_base_name,]}\n  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    knowledge_base_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def update_knowledge_base(
        self,
        knowledge_base_name: str,
        input: UpdateKnowledgeBaseInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """更新知识库

        Args:
            knowledge_base_name: 知识库名称
            input: 知识库配置

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 更新后的知识库对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.update_knowledge_base_with_options(
                knowledge_base_name,
                UpdateKnowledgeBaseRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api update_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[knowledge_base_name,input.to_map(),]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    knowledge_base_name,
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def update_knowledge_base_async(
        self,
        knowledge_base_name: str,
        input: UpdateKnowledgeBaseInput,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """更新知识库

        Args:
            knowledge_base_name: 知识库名称
            input: 知识库配置

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 更新后的知识库对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.update_knowledge_base_with_options_async(
                knowledge_base_name,
                UpdateKnowledgeBaseRequest(body=input),
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api update_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[knowledge_base_name,input.to_map(),]}\n  response:"
                f" {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    knowledge_base_name,
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def get_knowledge_base(
        self,
        knowledge_base_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """获取知识库

        Args:
            knowledge_base_name: 知识库名称

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 知识库对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.get_knowledge_base_with_options(
                knowledge_base_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api get_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[knowledge_base_name,]}\n  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    knowledge_base_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def get_knowledge_base_async(
        self,
        knowledge_base_name: str,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> KnowledgeBase:
        """获取知识库

        Args:
            knowledge_base_name: 知识库名称

            headers: 请求头
            config: 配置

        Returns:
            KnowledgeBase: 知识库对象

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.get_knowledge_base_with_options_async(
                knowledge_base_name,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api get_knowledge_base, request Request ID:"
                f" {response.body.request_id}\n  request:"
                f" {[knowledge_base_name,]}\n  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    knowledge_base_name,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e

    def list_knowledge_bases(
        self,
        input: ListKnowledgeBasesRequest,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> ListKnowledgeBasesOutput:
        """列出知识库

        Args:
            input: 查询参数

            headers: 请求头
            config: 配置

        Returns:
            ListKnowledgeBasesOutput: 知识库列表

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = client.list_knowledge_bases_with_options(
                input,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api list_knowledge_bases, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                pydash.get(e, "data.message", pydash.get(e, "message", "")),
                request_id=e.request_id,
            ) from e

    async def list_knowledge_bases_async(
        self,
        input: ListKnowledgeBasesRequest,
        headers: Optional[Dict[str, str]] = None,
        config: Optional[Config] = None,
    ) -> ListKnowledgeBasesOutput:
        """列出知识库

        Args:
            input: 查询参数

            headers: 请求头
            config: 配置

        Returns:
            ListKnowledgeBasesOutput: 知识库列表

        Raises:
            AgentRuntimeError: 调用失败时抛出
            ClientError: 客户端错误
            ServerError: 服务器错误
            APIError: 运行时错误
        """

        try:
            client = self._get_client(config)
            response = await client.list_knowledge_bases_with_options_async(
                input,
                headers=headers or {},
                runtime=RuntimeOptions(),
            )

            logger.debug(
                "request api list_knowledge_bases, request Request ID:"
                f" {response.body.request_id}\n  request: {[input.to_map(),]}\n"
                f"  response: {response.body.data}"
            )

            return response.body.data
        except ClientException as e:
            raise ClientError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
                request=[
                    input,
                ],
            ) from e
        except ServerException as e:
            raise ServerError(
                e.status_code,
                e.data.get("message", e.message),
                request_id=e.request_id,
            ) from e
